cc_binary (
  name = "000_-_RAII_(Resource_Acquisition_Is_Initialization)_-_snippet",
  srcs = ["000 - RAII (Resource Acquisition Is Initialization) - snippet.cc"],
)

cc_binary (
  name = "001_-_Templates_for_Type-Independent_Code_-_snippet",
  srcs = ["001 - Templates for Type-Independent Code - snippet.cc"],
)

cc_binary (
  name = "002_-_Multiple_Inheritance_-_snippet",
  srcs = ["002 - Multiple Inheritance - snippet.cc"],
)

cc_binary (
  name = "003_-_Operator_Overloading_-_snippet",
  srcs = ["003 - Operator Overloading - snippet.cc"],
)

cc_binary (
  name = "004_-_Friend_Functions_-_snippet",
  srcs = ["004 - Friend Functions - snippet.cc"],
)

cc_binary (
  name = "005_-_Exception_Handling_with_Try_and_Catch_Blocks_-_snippet",
  srcs = ["005 - Exception Handling with Try and Catch Blocks - snippet.cc"],
)

cc_binary (
  name = "006_-_Namespaces_for_Code_Organization_and_Avoiding_Name_Collisions_-_snippet",
  srcs = ["006 - Namespaces for Code Organization and Avoiding Name Collisions - snippet.cc"],
)

cc_binary (
  name = "007_-_Preprocessor_Directives_and_Macros_-_snippet",
  srcs = ["007 - Preprocessor Directives and Macros - snippet.cc"],
)

