cc_binary (
  name = "000_-_All_Math_&_Logic_Operators_-_snippet",
  srcs = ["000 - All Math & Logic Operators - snippet.cc"],
)

cc_binary (
  name = "001_-_Save_Navigation_-_snippet",
  srcs = ["001 - Save Navigation - snippet.cc"],
)

cc_binary (
  name = "002_-_Coalescing_-_snippet",
  srcs = ["002 - Coalescing - snippet.cc"],
)

cc_binary (
  name = "003_-_Comparison_-_snippet",
  srcs = ["003 - Comparison - snippet.cc"],
)

cc_binary (
  name = "004_-_Assignment_-_snippet",
  srcs = ["004 - Assignment - snippet.cc"],
)

cc_binary (
  name = "005_-_String_Concatenation_-_snippet",
  srcs = ["005 - String Concatenation - snippet.cc"],
)

cc_binary (
  name = "006_-_Reflection_-_snippet",
  srcs = ["006 - Reflection - snippet.cc"],
)

cc_binary (
  name = "007_-_Bitwise_-_snippet",
  srcs = ["007 - Bitwise - snippet.cc"],
)

cc_binary (
  name = "008_-_Boolean_Operators_on_Non-Boolean_Values_-_snippet",
  srcs = ["008 - Boolean Operators on Non-Boolean Values - snippet.cc"],
)

cc_binary (
  name = "009_-_Operator_Precedence_-_snippet",
  srcs = ["009 - Operator Precedence - snippet.cc"],
)

cc_binary (
  name = "010_-_Collection_Operators_-_snippet",
  srcs = ["010 - Collection Operators - snippet.cc"],
)

cc_binary (
  name = "011_-_String_Operators_-_snippet",
  srcs = ["011 - String Operators - snippet.cc"],
)

cc_binary (
  name = "012_-_Runtime_Type,_Type_Equality,_Type_Comparison_-_snippet",
  srcs = ["012 - Runtime Type, Type Equality, Type Comparison - snippet.cc"],
)

