cc_binary (
  name = "000_-_Functions_-_snippet",
  srcs = ["000 - Functions - snippet.cc"],
)

cc_binary (
  name = "001_-_Classes_-_snippet",
  srcs = ["001 - Classes - snippet.cc"],
)

cc_binary (
  name = "002_-_Variables_-_snippet",
  srcs = ["002 - Variables - snippet.cc"],
)

cc_binary (
  name = "003_-_Package,_File_-_snippet",
  srcs = ["003 - Package, File - snippet.cc"],
)

