cc_binary (
  name = "000_-_Function_Decorators_-_snippet",
  srcs = ["000 - Function Decorators - snippet.cc"],
)

cc_binary (
  name = "001_-_Class_Decorators_-_snippet",
  srcs = ["001 - Class Decorators - snippet.cc"],
)

cc_binary (
  name = "002_-_Useful_Built-In_Decorators_-_snippet",
  srcs = ["002 - Useful Built-In Decorators - snippet.cc"],
)

