cc_binary (
  name = "000_-_Lambdas_-_snippet",
  srcs = ["000 - Lambdas - snippet.cc"],
)

cc_binary (
  name = "001_-_Closures_(ref_vs._value)_-_snippet",
  srcs = ["001 - Closures (ref vs. value) - snippet.cc"],
)

cc_binary (
  name = "002_-_Ignored_Parameters_-_snippet",
  srcs = ["002 - Ignored Parameters - snippet.cc"],
)

cc_binary (
  name = "003_-_Partial_Application_-_snippet",
  srcs = ["003 - Partial Application - snippet.cc"],
)

cc_binary (
  name = "004_-_Bound_vs._Unbound_(eg._'this')_-_snippet",
  srcs = ["004 - Bound vs. Unbound (eg. 'this') - snippet.cc"],
)

cc_binary (
  name = "005_-_Declaration_of_Variable_Holding_Function_-_snippet",
  srcs = ["005 - Declaration of Variable Holding Function - snippet.cc"],
)

cc_binary (
  name = "006_-_map,_reduce,_and_filter_-_snippet",
  srcs = ["006 - map, reduce, and filter - snippet.cc"],
)

cc_binary (
  name = "007_-_Return_Object_from_Lambda_-_snippet",
  srcs = ["007 - Return Object from Lambda - snippet.cc"],
)

cc_binary (
  name = "008_-_Range_-_snippet",
  srcs = ["008 - Range - snippet.cc"],
)

cc_binary (
  name = "009_-_Functional_zip()_method_on_2_streams_-_snippet",
  srcs = ["009 - Functional zip() method on 2 streams - snippet.cc"],
)

cc_binary (
  name = "010_-_IIFE_-_snippet",
  srcs = ["010 - IIFE - snippet.cc"],
)

