cc_binary (
  name = "000_-_if,_then_statements_-_snippet",
  srcs = ["000 - if, then statements - snippet.cc"],
)

cc_binary (
  name = "001_-_if,_then,_else_statements_-_snippet",
  srcs = ["001 - if, then, else statements - snippet.cc"],
)

cc_binary (
  name = "002_-_switch_statements_-_snippet",
  srcs = ["002 - switch statements - snippet.cc"],
)

cc_binary (
  name = "003_-_Switch_Statements_on_Non-Integer_Types_(string,_enum,_custom)_-_snippet",
  srcs = ["003 - Switch Statements on Non-Integer Types (string, enum, custom) - snippet.cc"],
)

cc_binary (
  name = "004_-_for_loops_-_snippet",
  srcs = ["004 - for loops - snippet.cc"],
)

cc_binary (
  name = "005_-_while_loops_-_snippet",
  srcs = ["005 - while loops - snippet.cc"],
)

cc_binary (
  name = "006_-_do-while_loops_-_snippet",
  srcs = ["006 - do-while loops - snippet.cc"],
)

cc_binary (
  name = "007_-_break_and_continue_-_snippet",
  srcs = ["007 - break and continue - snippet.cc"],
)

cc_binary (
  name = "008_-_try,_catch,_finally_and_throwing_exceptions_-_snippet",
  srcs = ["008 - try, catch, finally and throwing exceptions - snippet.cc"],
)

cc_binary (
  name = "009_-_emptiness_checks_-_snippet",
  srcs = ["009 - emptiness checks - snippet.cc"],
)

cc_binary (
  name = "010_-_context_management_-_snippet",
  srcs = ["010 - context management - snippet.cc"],
)

cc_binary (
  name = "011_-_Context_Management_with_Multiple_Resources_at_Once_-_snippet",
  srcs = ["011 - Context Management with Multiple Resources at Once - snippet.cc"],
)

cc_binary (
  name = "012_-_asserts_-_snippet",
  srcs = ["012 - asserts - snippet.cc"],
)

cc_binary (
  name = "013_-_when_braces_are_required_vs._optional_-_snippet",
  srcs = ["013 - when braces are required vs. optional - snippet.cc"],
)

cc_binary (
  name = "014_-_Generator,_Lazy_List_-_snippet",
  srcs = ["014 - Generator, Lazy List - snippet.cc"],
)

cc_binary (
  name = "015_-_Arguments_to_main()_function_-_snippet",
  srcs = ["015 - Arguments to main() function - snippet.cc"],
)

cc_binary (
  name = "016_-_Truthiness_of_Different_Data_Types_in_Boolean_Conditions_-_snippet",
  srcs = ["016 - Truthiness of Different Data Types in Boolean Conditions - snippet.cc"],
)

cc_binary (
  name = "017_-_Actual_Value_Returned_by_Short-Circuiting_-_snippet",
  srcs = ["017 - Actual Value Returned by Short-Circuiting - snippet.cc"],
)

cc_binary (
  name = "018_-_Use_of_final_or_constant_variable_in_loop_headers_-_snippet",
  srcs = ["018 - Use of final or constant variable in loop headers - snippet.cc"],
)

