cc_binary (
  name = "000_-_Function_Declaration_vs._Body_-_snippet",
  srcs = ["000 - Function Declaration vs. Body - snippet.cc"],
)

cc_binary (
  name = "001_-_Class_Declaration_vs._Body_-_snippet",
  srcs = ["001 - Class Declaration vs. Body - snippet.cc"],
)

cc_binary (
  name = "002_-_Variable_Declaration_vs._Implementation_-_snippet",
  srcs = ["002 - Variable Declaration vs. Implementation - snippet.cc"],
)

cc_binary (
  name = "003_-_Template_Declaration_vs._Implementation_-_snippet",
  srcs = ["003 - Template Declaration vs. Implementation - snippet.cc"],
)

cc_binary (
  name = "004_-_Forward_Declarations_-_snippet",
  srcs = ["004 - Forward Declarations - snippet.cc"],
)

cc_binary (
  name = "005_-_Instantiating_Templates_-_snippet",
  srcs = ["005 - Instantiating Templates - snippet.cc"],
)

cc_binary (
  name = "006_-_external_vs._internal_linkage_-_snippet",
  srcs = ["006 - external vs. internal linkage - snippet.cc"],
)

cc_binary (
  name = "007_-_external_variables_-_snippet",
  srcs = ["007 - external variables - snippet.cc"],
)

cc_binary (
  name = "008_-_external_functions_-_snippet",
  srcs = ["008 - external functions - snippet.cc"],
)

cc_binary (
  name = "009_-_global_variable_linkage_-_snippet",
  srcs = ["009 - global variable linkage - snippet.cc"],
)

