cc_binary (
  name = "000_-_Boost:_Provides_support_for_tasks_such_as_multithreading,_regular_expressions,_and_unit_testing._-_snippet",
  srcs = ["000 - Boost: Provides support for tasks such as multithreading, regular expressions, and unit testing. - snippet.cc"],
)

cc_binary (
  name = "001_-_Qt:_A_comprehensive_library_for_creating_GUI_applications._-_snippet",
  srcs = ["001 - Qt: A comprehensive library for creating GUI applications. - snippet.cc"],
)

cc_binary (
  name = "002_-_POCO:_A_collection_of_open-source_C++_class_libraries_that_simplify_network-based,_portable_applications._-_snippet",
  srcs = ["002 - POCO: A collection of open-source C++ class libraries that simplify network-based, portable applications. - snippet.cc"],
)

cc_binary (
  name = "003_-_OpenCV:_A_library_of_programming_functions_mainly_aimed_at_real-time_computer_vision._-_snippet",
  srcs = ["003 - OpenCV: A library of programming functions mainly aimed at real-time computer vision. - snippet.cc"],
)

cc_binary (
  name = "004_-_Eigen:_A_high-level_C++_library_of_template_headers_for_linear_algebra,_matrix_and_vector_operations,_numerical_solvers_and_related_algorithms._-_snippet",
  srcs = ["004 - Eigen: A high-level C++ library of template headers for linear algebra, matrix and vector operations, numerical solvers and related algorithms. - snippet.cc"],
)

cc_binary (
  name = "005_-_Google_Test:_Google's_framework_for_writing_C++_tests_on_a_variety_of_platforms._-_snippet",
  srcs = ["005 - Google Test: Google's framework for writing C++ tests on a variety of platforms. - snippet.cc"],
)

cc_binary (
  name = "006_-_SFML:_Simple_and_Fast_Multimedia_Library_for_handling_windows,_graphics,_audio,_etc._-_snippet",
  srcs = ["006 - SFML: Simple and Fast Multimedia Library for handling windows, graphics, audio, etc. - snippet.cc"],
)

