cc_binary (
  name = "000_-_Basic_Syntax_and_Instantiation_(inc._static,_instance,_class_members,_etc.)_-_snippet",
  srcs = ["000 - Basic Syntax and Instantiation (inc. static, instance, class members, etc.) - snippet.cc"],
)

cc_binary (
  name = "001_-_Static_Classes_-_snippet",
  srcs = ["001 - Static Classes - snippet.cc"],
)

cc_binary (
  name = "002_-_Static_Constructor_-_snippet",
  srcs = ["002 - Static Constructor - snippet.cc"],
)

cc_binary (
  name = "003_-_Access_Modifiers_-_snippet",
  srcs = ["003 - Access Modifiers - snippet.cc"],
)

cc_binary (
  name = "004_-_Inheritance_-_snippet",
  srcs = ["004 - Inheritance - snippet.cc"],
)

cc_binary (
  name = "005_-_Interfaces_and_Abstract_Base_Classes_-_snippet",
  srcs = ["005 - Interfaces and Abstract Base Classes - snippet.cc"],
)

cc_binary (
  name = "006_-_Multiple_Inheritance_-_snippet",
  srcs = ["006 - Multiple Inheritance - snippet.cc"],
)

cc_binary (
  name = "007_-_Polymorphism_-_snippet",
  srcs = ["007 - Polymorphism - snippet.cc"],
)

cc_binary (
  name = "008_-_Nullability_of_Class_Members_-_snippet",
  srcs = ["008 - Nullability of Class Members - snippet.cc"],
)

cc_binary (
  name = "009_-_Initializing_Instance_Values_in_Class_Declarations_-_snippet",
  srcs = ["009 - Initializing Instance Values in Class Declarations - snippet.cc"],
)

cc_binary (
  name = "010_-_Constructors,_Initialization_Lists_-_snippet",
  srcs = ["010 - Constructors, Initialization Lists - snippet.cc"],
)

cc_binary (
  name = "011_-_Base_and_Delegating_Constructors_-_snippet",
  srcs = ["011 - Base and Delegating Constructors - snippet.cc"],
)

cc_binary (
  name = "012_-_Constructors_Included_by_Default_-_snippet",
  srcs = ["012 - Constructors Included by Default - snippet.cc"],
)

cc_binary (
  name = "013_-_Calling_Base_Class_Method_from_Derived_Class_Method_-_snippet",
  srcs = ["013 - Calling Base Class Method from Derived Class Method - snippet.cc"],
)

cc_binary (
  name = "014_-_this,_self_Keyword_-_snippet",
  srcs = ["014 - this, self Keyword - snippet.cc"],
)

cc_binary (
  name = "015_-_Name_Hiding_-_snippet",
  srcs = ["015 - Name Hiding - snippet.cc"],
)

cc_binary (
  name = "016_-_Construction_Order_-_snippet",
  srcs = ["016 - Construction Order - snippet.cc"],
)

cc_binary (
  name = "017_-_Nested_Classes_-_snippet",
  srcs = ["017 - Nested Classes - snippet.cc"],
)

cc_binary (
  name = "018_-_Dynamic_Types_-_snippet",
  srcs = ["018 - Dynamic Types - snippet.cc"],
)

cc_binary (
  name = "019_-_Operator_Overloading_-_snippet",
  srcs = ["019 - Operator Overloading - snippet.cc"],
)

cc_binary (
  name = "020_-_Indexers_-_snippet",
  srcs = ["020 - Indexers - snippet.cc"],
)

cc_binary (
  name = "021_-_Copying,_Cloning_-_snippet",
  srcs = ["021 - Copying, Cloning - snippet.cc"],
)

cc_binary (
  name = "022_-_Boxing,_Unboxing_-_snippet",
  srcs = ["022 - Boxing, Unboxing - snippet.cc"],
)

cc_binary (
  name = "023_-_Root_Class_of_Type_System_(and_methods_to_override)_-_snippet",
  srcs = ["023 - Root Class of Type System (and methods to override) - snippet.cc"],
)

cc_binary (
  name = "024_-_Useful_Built-in_Interfaces_and_Abstract_Base_Classes_-_snippet",
  srcs = ["024 - Useful Built-in Interfaces and Abstract Base Classes - snippet.cc"],
)

cc_binary (
  name = "025_-_Importance_of_Declaration_Order,_Forward_Declarations_-_snippet",
  srcs = ["025 - Importance of Declaration Order, Forward Declarations - snippet.cc"],
)

cc_binary (
  name = "026_-_Structural_typing_-_snippet",
  srcs = ["026 - Structural typing - snippet.cc"],
)

cc_binary (
  name = "027_-_Partial_Classes_-_snippet",
  srcs = ["027 - Partial Classes - snippet.cc"],
)

cc_binary (
  name = "028_-_Reference_Type_vs._Value_Type_-_snippet",
  srcs = ["028 - Reference Type vs. Value Type - snippet.cc"],
)

cc_binary (
  name = "029_-_Properties_(manual_and_auto-implemented)_-_snippet",
  srcs = ["029 - Properties (manual and auto-implemented) - snippet.cc"],
)

cc_binary (
  name = "030_-_Return_Type_Inference_-_snippet",
  srcs = ["030 - Return Type Inference - snippet.cc"],
)

cc_binary (
  name = "031_-_Destructors,_Finalizers,_Disposable_Pattern_-_snippet",
  srcs = ["031 - Destructors, Finalizers, Disposable Pattern - snippet.cc"],
)

cc_binary (
  name = "032_-_Callable_Object,_Call_Operator_-_snippet",
  srcs = ["032 - Callable Object, Call Operator - snippet.cc"],
)

cc_binary (
  name = "033_-_Anonymous_Class_-_snippet",
  srcs = ["033 - Anonymous Class - snippet.cc"],
)

cc_binary (
  name = "034_-_Static_and_Default_Methods_in_Interfaces_-_snippet",
  srcs = ["034 - Static and Default Methods in Interfaces - snippet.cc"],
)

cc_binary (
  name = "035_-_Interface_Member_Visibility_(default_and_modifiers)_-_snippet",
  srcs = ["035 - Interface Member Visibility (default and modifiers) - snippet.cc"],
)

cc_binary (
  name = "036_-_Interface_Members_Other_Than_Public_Abstract_Methods_-_snippet",
  srcs = ["036 - Interface Members Other Than Public Abstract Methods - snippet.cc"],
)

cc_binary (
  name = "037_-_Sealed,_Final_Methods_-_snippet",
  srcs = ["037 - Sealed, Final Methods - snippet.cc"],
)

cc_binary (
  name = "038_-_Sealed,_Final_Classes_-_snippet",
  srcs = ["038 - Sealed, Final Classes - snippet.cc"],
)

cc_binary (
  name = "039_-_Caveats_for_Subclass_Constructors_(eg._when_to_call_base,_construction_order,_etc.)_-_snippet",
  srcs = ["039 - Caveats for Subclass Constructors (eg. when to call base, construction order, etc.) - snippet.cc"],
)

cc_binary (
  name = "040_-_Instances_Accessing_Each_Others'_Private_Members_-_snippet",
  srcs = ["040 - Instances Accessing Each Others' Private Members - snippet.cc"],
)

cc_binary (
  name = "041_-_Friend_Classes_-_snippet",
  srcs = ["041 - Friend Classes - snippet.cc"],
)

cc_binary (
  name = "042_-_Method_Name_Collisions_in_Interfaces_Implemented_by_Class_-_snippet",
  srcs = ["042 - Method Name Collisions in Interfaces Implemented by Class - snippet.cc"],
)

cc_binary (
  name = "043_-_Partial_Interface_Implementation_-_snippet",
  srcs = ["043 - Partial Interface Implementation - snippet.cc"],
)

cc_binary (
  name = "044_-_Covariant_Return_Types_-_snippet",
  srcs = ["044 - Covariant Return Types - snippet.cc"],
)

cc_binary (
  name = "045_-_Inheritance_and_Name_Hiding_of_Static_Members_-_snippet",
  srcs = ["045 - Inheritance and Name Hiding of Static Members - snippet.cc"],
)

cc_binary (
  name = "046_-_Hashing_Members_Together_-_snippet",
  srcs = ["046 - Hashing Members Together - snippet.cc"],
)

