cc_binary (
  name = "000_-_Console_I,_O_-_snippet",
  srcs = ["000 - Console I, O - snippet.cc"],
)

cc_binary (
  name = "001_-_Idiomatic_User_Input_(Lines_and_Chunks)_-_snippet",
  srcs = ["001 - Idiomatic User Input (Lines and Chunks) - snippet.cc"],
)

cc_binary (
  name = "002_-_Math_-_snippet",
  srcs = ["002 - Math - snippet.cc"],
)

cc_binary (
  name = "003_-_File_I,_O_-_snippet",
  srcs = ["003 - File I, O - snippet.cc"],
)

cc_binary (
  name = "004_-_Threading,_async,_await,_lock,_promise,_mutex_-_snippet",
  srcs = ["004 - Threading, async, await, lock, promise, mutex - snippet.cc"],
)

cc_binary (
  name = "005_-_HTTP_-_snippet",
  srcs = ["005 - HTTP - snippet.cc"],
)

cc_binary (
  name = "006_-_Paths_and_Environment_Variables_-_snippet",
  srcs = ["006 - Paths and Environment Variables - snippet.cc"],
)

cc_binary (
  name = "007_-_Events_-_snippet",
  srcs = ["007 - Events - snippet.cc"],
)

cc_binary (
  name = "008_-_Observables,_Reactive_Programming_-_snippet",
  srcs = ["008 - Observables, Reactive Programming - snippet.cc"],
)

cc_binary (
  name = "009_-_Time_and_Dates_-_snippet",
  srcs = ["009 - Time and Dates - snippet.cc"],
)

