cc_binary (
  name = "000_-_C++98_(1998):_The_first_standardized_version_of_C++._-_snippet",
  srcs = ["000 - C++98 (1998): The first standardized version of C++. - snippet.cc"],
)

cc_binary (
  name = "001_-_C++03_(2003):_Minor_update_to_C++98._-_snippet",
  srcs = ["001 - C++03 (2003): Minor update to C++98. - snippet.cc"],
)

cc_binary (
  name = "002_-_C++11_(2011):_Major_update_with_many_new_features_like_auto_keyword,_range-based_for_loops,_lambda_functions,_etc._-_snippet",
  srcs = ["002 - C++11 (2011): Major update with many new features like auto keyword, range-based for loops, lambda functions, etc. - snippet.cc"],
)

cc_binary (
  name = "003_-_C++14_(2014):_Minor_update_with_improved_lambda_functions,_digit_separators,_etc._-_snippet",
  srcs = ["003 - C++14 (2014): Minor update with improved lambda functions, digit separators, etc. - snippet.cc"],
)

cc_binary (
  name = "004_-_C++17_(2017):_Major_update_with_new_features_like_structured_bindings,_constexpr_if,_etc._-_snippet",
  srcs = ["004 - C++17 (2017): Major update with new features like structured bindings, constexpr if, etc. - snippet.cc"],
)

cc_binary (
  name = "005_-_C++20_(2020):_Latest_version_with_features_like_modules,_coroutines,_concepts,_etc._-_snippet",
  srcs = ["005 - C++20 (2020): Latest version with features like modules, coroutines, concepts, etc. - snippet.cc"],
)

