cc_binary (
  name = "000_-_Array_-_snippet",
  srcs = ["000 - Array - snippet.cc"],
)

cc_binary (
  name = "001_-_List_-_snippet",
  srcs = ["001 - List - snippet.cc"],
)

cc_binary (
  name = "002_-_Vector_-_snippet",
  srcs = ["002 - Vector - snippet.cc"],
)

cc_binary (
  name = "003_-_Dictionary,_Map_-_snippet",
  srcs = ["003 - Dictionary, Map - snippet.cc"],
)

cc_binary (
  name = "004_-_Set_-_snippet",
  srcs = ["004 - Set - snippet.cc"],
)

cc_binary (
  name = "005_-_String_Builder_-_snippet",
  srcs = ["005 - String Builder - snippet.cc"],
)

cc_binary (
  name = "006_-_Tuple_-_snippet",
  srcs = ["006 - Tuple - snippet.cc"],
)

cc_binary (
  name = "007_-_Struct_-_snippet",
  srcs = ["007 - Struct - snippet.cc"],
)

cc_binary (
  name = "008_-_Immutable_Types_-_snippet",
  srcs = ["008 - Immutable Types - snippet.cc"],
)

cc_binary (
  name = "009_-_String_as_Collection_-_snippet",
  srcs = ["009 - String as Collection - snippet.cc"],
)

cc_binary (
  name = "010_-_Generic_Sequence,_Iterable_Type_-_snippet",
  srcs = ["010 - Generic Sequence, Iterable Type - snippet.cc"],
)

cc_binary (
  name = "011_-_Aggregate_functions_(max,_min,_etc.)_-_snippet",
  srcs = ["011 - Aggregate functions (max, min, etc.) - snippet.cc"],
)

cc_binary (
  name = "012_-_Iterating_Keys_vs._Values_-_snippet",
  srcs = ["012 - Iterating Keys vs. Values - snippet.cc"],
)

cc_binary (
  name = "013_-_Zipping_-_snippet",
  srcs = ["013 - Zipping - snippet.cc"],
)

cc_binary (
  name = "014_-_Slicing_-_snippet",
  srcs = ["014 - Slicing - snippet.cc"],
)

cc_binary (
  name = "015_-_Sorting_-_snippet",
  srcs = ["015 - Sorting - snippet.cc"],
)

cc_binary (
  name = "016_-_Stack,_Queue,_Deque_-_snippet",
  srcs = ["016 - Stack, Queue, Deque - snippet.cc"],
)

cc_binary (
  name = "017_-_Collection_Literals_and_Inline_Initialization,_Passing_-_snippet",
  srcs = ["017 - Collection Literals and Inline Initialization, Passing - snippet.cc"],
)

cc_binary (
  name = "018_-_Builder_Pattern_-_snippet",
  srcs = ["018 - Builder Pattern - snippet.cc"],
)

cc_binary (
  name = "019_-_Index_Operator_-_snippet",
  srcs = ["019 - Index Operator - snippet.cc"],
)

cc_binary (
  name = "020_-_Conversions_Between_Collection_Types_-_snippet",
  srcs = ["020 - Conversions Between Collection Types - snippet.cc"],
)

cc_binary (
  name = "021_-_Ordered_vs._Unordered_Maps,_Dictionaries_-_snippet",
  srcs = ["021 - Ordered vs. Unordered Maps, Dictionaries - snippet.cc"],
)

cc_binary (
  name = "022_-_Sorting_(Default_vs._Custom_Comparator)_-_snippet",
  srcs = ["022 - Sorting (Default vs. Custom Comparator) - snippet.cc"],
)

cc_binary (
  name = "023_-_Casting_Between_More_and_Less_Specific_Element_Types_in_Collection_References_-_snippet",
  srcs = ["023 - Casting Between More and Less Specific Element Types in Collection References - snippet.cc"],
)

cc_binary (
  name = "024_-_Copying,_Cloning_-_snippet",
  srcs = ["024 - Copying, Cloning - snippet.cc"],
)

cc_binary (
  name = "025_-_Uniformly_Initializing_Elements_(eg._to_default_or_non-default_values_based_on_type)_-_snippet",
  srcs = ["025 - Uniformly Initializing Elements (eg. to default or non-default values based on type) - snippet.cc"],
)

cc_binary (
  name = "026_-_Shuffling_-_snippet",
  srcs = ["026 - Shuffling - snippet.cc"],
)

cc_binary (
  name = "027_-_Priority_Queue,_Minheap,_Maxheap_-_snippet",
  srcs = ["027 - Priority Queue, Minheap, Maxheap - snippet.cc"],
)

cc_binary (
  name = "028_-_Skipping_Items_in_Array_Initializer?_-_snippet",
  srcs = ["028 - Skipping Items in Array Initializer? - snippet.cc"],
)

cc_binary (
  name = "029_-_Sorted_Versions_of_Collection_Types_-_snippet",
  srcs = ["029 - Sorted Versions of Collection Types - snippet.cc"],
)

cc_binary (
  name = "030_-_Bitfields_-_snippet",
  srcs = ["030 - Bitfields - snippet.cc"],
)

cc_binary (
  name = "031_-_Thread_Safety_of_Built-in_Data_Types_and_Collections_-_snippet",
  srcs = ["031 - Thread Safety of Built-in Data Types and Collections - snippet.cc"],
)

cc_binary (
  name = "032_-_Thread-Safe_Alternatives_to_Built-in_Types_and_Collections_-_snippet",
  srcs = ["032 - Thread-Safe Alternatives to Built-in Types and Collections - snippet.cc"],
)

cc_binary (
  name = "033_-_Searching_-_snippet",
  srcs = ["033 - Searching - snippet.cc"],
)

