cc_binary (
  name = "000_-_All_Ways_to_Quote_Strings_-_snippet",
  srcs = ["000 - All Ways to Quote Strings - snippet.cc"],
)

cc_binary (
  name = "001_-_Character_Types_and_Quoting_-_snippet",
  srcs = ["001 - Character Types and Quoting - snippet.cc"],
)

cc_binary (
  name = "002_-_Formatted_and_Template_Strings_-_snippet",
  srcs = ["002 - Formatted and Template Strings - snippet.cc"],
)

cc_binary (
  name = "003_-_String_Methods_-_snippet",
  srcs = ["003 - String Methods - snippet.cc"],
)

cc_binary (
  name = "004_-_String_Concatenation_-_snippet",
  srcs = ["004 - String Concatenation - snippet.cc"],
)

cc_binary (
  name = "005_-_Conversions_To,_From_String_-_snippet",
  srcs = ["005 - Conversions To, From String - snippet.cc"],
)

cc_binary (
  name = "006_-_Encodings_-_snippet",
  srcs = ["006 - Encodings - snippet.cc"],
)

cc_binary (
  name = "007_-_Printing_-_snippet",
  srcs = ["007 - Printing - snippet.cc"],
)

cc_binary (
  name = "008_-_Logging_-_snippet",
  srcs = ["008 - Logging - snippet.cc"],
)

cc_binary (
  name = "009_-_Regular_Expressions_-_snippet",
  srcs = ["009 - Regular Expressions - snippet.cc"],
)

cc_binary (
  name = "010_-_Serialization_-_snippet",
  srcs = ["010 - Serialization - snippet.cc"],
)

cc_binary (
  name = "011_-_StringBuilder,_StringBuffer,_etc._-_snippet",
  srcs = ["011 - StringBuilder, StringBuffer, etc. - snippet.cc"],
)

cc_binary (
  name = "012_-_Index_Operator_and_Slicing_-_snippet",
  srcs = ["012 - Index Operator and Slicing - snippet.cc"],
)

cc_binary (
  name = "013_-_Converting_Collections_to_String_-_snippet",
  srcs = ["013 - Converting Collections to String - snippet.cc"],
)

cc_binary (
  name = "014_-_Interop_Between_Characters_and_Numbers_-_snippet",
  srcs = ["014 - Interop Between Characters and Numbers - snippet.cc"],
)

cc_binary (
  name = "015_-_Comments_(block,_line,_etc.)_-_snippet",
  srcs = ["015 - Comments (block, line, etc.) - snippet.cc"],
)

cc_binary (
  name = "016_-_String_Splitting_-_snippet",
  srcs = ["016 - String Splitting - snippet.cc"],
)

cc_binary (
  name = "017_-_Sorting_-_snippet",
  srcs = ["017 - Sorting - snippet.cc"],
)

cc_binary (
  name = "018_-_Line_Endings_(In_Literals_and_Relative_to_System)_-_snippet",
  srcs = ["018 - Line Endings (In Literals and Relative to System) - snippet.cc"],
)

