cc_binary (
  name = "000_-_Importing_Built-In_Libraries_-_snippet",
  srcs = ["000 - Importing Built-In Libraries - snippet.cc"],
)

cc_binary (
  name = "001_-_Declaring_Importable_Module,_Package_-_snippet",
  srcs = ["001 - Declaring Importable Module, Package - snippet.cc"],
)

cc_binary (
  name = "002_-_Importing_Custom_Module,_Package_by_Relative_path_from_Subfolder_-_snippet",
  srcs = ["002 - Importing Custom Module, Package by Relative path from Subfolder - snippet.cc"],
)

cc_binary (
  name = "003_-_Other_Package_Management_Options_-_snippet",
  srcs = ["003 - Other Package Management Options - snippet.cc"],
)

cc_binary (
  name = "004_-_Renaming_Imported_Symbols_-_snippet",
  srcs = ["004 - Renaming Imported Symbols - snippet.cc"],
)

cc_binary (
  name = "005_-_Wrapping_Multiple_Imported_Symbols_-_snippet",
  srcs = ["005 - Wrapping Multiple Imported Symbols - snippet.cc"],
)

cc_binary (
  name = "006_-_Exporting_and_Access_levels_-_snippet",
  srcs = ["006 - Exporting and Access levels - snippet.cc"],
)

cc_binary (
  name = "007_-_Multiple_Imports_on_One_Line_-_snippet",
  srcs = ["007 - Multiple Imports on One Line - snippet.cc"],
)

cc_binary (
  name = "008_-_Barrelling_-_snippet",
  srcs = ["008 - Barrelling - snippet.cc"],
)

cc_binary (
  name = "009_-_Statefulness_of_Imported_Packages_-_snippet",
  srcs = ["009 - Statefulness of Imported Packages - snippet.cc"],
)

cc_binary (
  name = "010_-_Namespaces_-_snippet",
  srcs = ["010 - Namespaces - snippet.cc"],
)

cc_binary (
  name = "011_-_Ambient_Declarations_-_snippet",
  srcs = ["011 - Ambient Declarations - snippet.cc"],
)

cc_binary (
  name = "012_-_Search_Path_-_snippet",
  srcs = ["012 - Search Path - snippet.cc"],
)

cc_binary (
  name = "013_-_Importing_Constants_and_Variables_-_snippet",
  srcs = ["013 - Importing Constants and Variables - snippet.cc"],
)

cc_binary (
  name = "014_-_Default_Imports_in_Every_Program_-_snippet",
  srcs = ["014 - Default Imports in Every Program - snippet.cc"],
)

cc_binary (
  name = "015_-_Multiple_Top-Level_Classes_in_Same_File_-_snippet",
  srcs = ["015 - Multiple Top-Level Classes in Same File - snippet.cc"],
)

cc_binary (
  name = "016_-_Top-Level_Classes_Referring_to_Each_Other_Mutually_-_snippet",
  srcs = ["016 - Top-Level Classes Referring to Each Other Mutually - snippet.cc"],
)

cc_binary (
  name = "017_-_Top-Level_Functions_(not_in_classes)_-_snippet",
  srcs = ["017 - Top-Level Functions (not in classes) - snippet.cc"],
)

cc_binary (
  name = "018_-_Top-Level_Variables,_Constants_(not_in_classes)_-_snippet",
  srcs = ["018 - Top-Level Variables, Constants (not in classes) - snippet.cc"],
)

cc_binary (
  name = "019_-_Top-Level_Enums_(not_in_classes)_-_snippet",
  srcs = ["019 - Top-Level Enums (not in classes) - snippet.cc"],
)

cc_binary (
  name = "020_-_Fully-Qualified_Symbol_Usages_Without_Importing_First_-_snippet",
  srcs = ["020 - Fully-Qualified Symbol Usages Without Importing First - snippet.cc"],
)

cc_binary (
  name = "021_-_Dealing_With_Symbol_Name_Conflicts_-_snippet",
  srcs = ["021 - Dealing With Symbol Name Conflicts - snippet.cc"],
)

