cc_binary (
  name = "000_-_Test_Class,_Suite_and_Methods_-_snippet",
  srcs = ["000 - Test Class, Suite and Methods - snippet.cc"],
)

cc_binary (
  name = "001_-_Setup_and_Teardown_-_snippet",
  srcs = ["001 - Setup and Teardown - snippet.cc"],
)

cc_binary (
  name = "002_-_Persistence_of_Class,_Suite_Data_Between_Tests_-_snippet",
  srcs = ["002 - Persistence of Class, Suite Data Between Tests - snippet.cc"],
)

cc_binary (
  name = "003_-_Asserts_-_snippet",
  srcs = ["003 - Asserts - snippet.cc"],
)

cc_binary (
  name = "004_-_Mocking_-_snippet",
  srcs = ["004 - Mocking - snippet.cc"],
)

cc_binary (
  name = "005_-_Faking_-_snippet",
  srcs = ["005 - Faking - snippet.cc"],
)

cc_binary (
  name = "006_-_Screendiffs_-_snippet",
  srcs = ["006 - Screendiffs - snippet.cc"],
)

