cc_binary (
  name = "000_-_Generic_Function_-_snippet",
  srcs = ["000 - Generic Function - snippet.cc"],
)

cc_binary (
  name = "001_-_Explicitly_Calling_Generic_Function_with_Type_-_snippet",
  srcs = ["001 - Explicitly Calling Generic Function with Type - snippet.cc"],
)

cc_binary (
  name = "002_-_Generic_Class_-_snippet",
  srcs = ["002 - Generic Class - snippet.cc"],
)

cc_binary (
  name = "003_-_Explicitly_Creating_Generic_Class_with_Type_-_snippet",
  srcs = ["003 - Explicitly Creating Generic Class with Type - snippet.cc"],
)

cc_binary (
  name = "004_-_Generic_Lambda_-_snippet",
  srcs = ["004 - Generic Lambda - snippet.cc"],
)

cc_binary (
  name = "005_-_Important_Built-in_Generic_Classes,_Interfaces_-_snippet",
  srcs = ["005 - Important Built-in Generic Classes, Interfaces - snippet.cc"],
)

cc_binary (
  name = "006_-_Void_as_T_argument_-_snippet",
  srcs = ["006 - Void as T argument - snippet.cc"],
)

cc_binary (
  name = "007_-_Metaprogramming_-_snippet",
  srcs = ["007 - Metaprogramming - snippet.cc"],
)

cc_binary (
  name = "008_-_Type_Erasure,_Runtime_Type,_Raw_Types_in_Code_-_snippet",
  srcs = ["008 - Type Erasure, Runtime Type, Raw Types in Code - snippet.cc"],
)

cc_binary (
  name = "009_-_Type_Constraints_-_snippet",
  srcs = ["009 - Type Constraints - snippet.cc"],
)

cc_binary (
  name = "010_-_Type_Wildcards_-_snippet",
  srcs = ["010 - Type Wildcards - snippet.cc"],
)

cc_binary (
  name = "011_-_Overloading_Generic_by_Number_of_Type_Parameters_-_snippet",
  srcs = ["011 - Overloading Generic by Number of Type Parameters - snippet.cc"],
)

cc_binary (
  name = "012_-_Covariance,_Contravariance_-_snippet",
  srcs = ["012 - Covariance, Contravariance - snippet.cc"],
)

cc_binary (
  name = "013_-_Custom_Comparators_for_Elements_-_snippet",
  srcs = ["013 - Custom Comparators for Elements - snippet.cc"],
)

cc_binary (
  name = "014_-_Built-in_Comparators_for_Elements_-_snippet",
  srcs = ["014 - Built-in Comparators for Elements - snippet.cc"],
)

cc_binary (
  name = "015_-_Curiously_Recurring_Template_Pattern_(CRTP)_-_snippet",
  srcs = ["015 - Curiously Recurring Template Pattern (CRTP) - snippet.cc"],
)

