cc_binary (
  name = "000_-_Basic_Syntax_-_snippet",
  srcs = ["000 - Basic Syntax - snippet.cc"],
)

cc_binary (
  name = "001_-_Positional_Arguments_-_snippet",
  srcs = ["001 - Positional Arguments - snippet.cc"],
)

cc_binary (
  name = "002_-_Named_Arguments_-_snippet",
  srcs = ["002 - Named Arguments - snippet.cc"],
)

cc_binary (
  name = "003_-_Optional,_Default_Arguments_-_snippet",
  srcs = ["003 - Optional, Default Arguments - snippet.cc"],
)

cc_binary (
  name = "004_-_Variadic_Functions_-_snippet",
  srcs = ["004 - Variadic Functions - snippet.cc"],
)

cc_binary (
  name = "005_-_Overloading_-_snippet",
  srcs = ["005 - Overloading - snippet.cc"],
)

cc_binary (
  name = "006_-_Lambdas_-_snippet",
  srcs = ["006 - Lambdas - snippet.cc"],
)

cc_binary (
  name = "007_-_Nested_Functions_-_snippet",
  srcs = ["007 - Nested Functions - snippet.cc"],
)

cc_binary (
  name = "008_-_Spread_Operator_-_snippet",
  srcs = ["008 - Spread Operator - snippet.cc"],
)

cc_binary (
  name = "009_-_Return_Type_Inference_-_snippet",
  srcs = ["009 - Return Type Inference - snippet.cc"],
)

cc_binary (
  name = "010_-_Higher-Order_Functions_-_snippet",
  srcs = ["010 - Higher-Order Functions - snippet.cc"],
)

cc_binary (
  name = "011_-_Inline_Functions_-_snippet",
  srcs = ["011 - Inline Functions - snippet.cc"],
)

cc_binary (
  name = "012_-_Macros_-_snippet",
  srcs = ["012 - Macros - snippet.cc"],
)

cc_binary (
  name = "013_-_Extension_Methods_-_snippet",
  srcs = ["013 - Extension Methods - snippet.cc"],
)

cc_binary (
  name = "014_-_Specifying_Exceptions_Thrown_by_Function_-_snippet",
  srcs = ["014 - Specifying Exceptions Thrown by Function - snippet.cc"],
)

cc_binary (
  name = "015_-_Recursion_-_snippet",
  srcs = ["015 - Recursion - snippet.cc"],
)

cc_binary (
  name = "016_-_Trailing_Commas_Allowed_in_Functions_and_Literals?_-_snippet",
  srcs = ["016 - Trailing Commas Allowed in Functions and Literals? - snippet.cc"],
)

cc_binary (
  name = "017_-_Passing_by_Reference_(modifying_a_nonlocal_variable_passed_to_a_function)_-_snippet",
  srcs = ["017 - Passing by Reference (modifying a nonlocal variable passed to a function) - snippet.cc"],
)

cc_binary (
  name = "018_-_Const,_final_Arguments_-_snippet",
  srcs = ["018 - Const, final Arguments - snippet.cc"],
)

cc_binary (
  name = "019_-_Uniqueness_of_Method_Signature_(param_names?__param_types?_overloads?)_-_snippet",
  srcs = ["019 - Uniqueness of Method Signature (param names?  param types? overloads?) - snippet.cc"],
)

